### PR TITLE
Translation of NTFS specification into English

### PR DESCRIPTION
**Pull request by woshilapin**
This is only a Work In progress for translating the NTFS specification in English (I copied over the French version and translated only the first part). I'm sure a lot of what I started is not accurate enough, some better jargon might be available... the goal is to use this PR to discuss, improve and finally provide an English version of this specification.

Note: I created this PR as a draft PR for now. You're welcome to contribute a paragraph (or more), let me know if you can't push on my branch (maybe we can create the branch directly on the Navitia repository for ease of contribution?).

### CODE REVIEW

**Review by pbougue — COMMENTED** [review]
As far as I remembered, deepl.com could do a great job for a first pass of translation :wink: 
To be discussed, but my vote is (in order of priority):
1. Have only one spec (2 versions are gonna be desynchronized, and sync with code already is not pretty)
2. If I have to vote, I vote for :gb: version (but @prhod as a sharper opinion on that and was for :fr: so far if I'm correct)

**Comment by woshilapin** [comment]
> 1. Have only one spec (2 versions are gonna be desynchronized, and sync with code already is not pretty)

If we decide to go that way, this PR could be about dumping the French version too.

> 2. If I have to vote, I vote for gb version (but @prhod as a sharper opinion on that and was for fr so far if I'm correct)

We'll see when he's back but he wrote the [NTFS Fares Specification](https://github.com/CanalTP/ntfs-specification/blob/master/ntfs_fare_extension.md) in English :wink:

NB: For DeepL, I'm not opposed to do a first pass with an automatic translator but:
- I usually found it's harder to modify something that exists than creating from scratch (even if DeepL is of pretty good quality so it might be that there is not so much corrections to do)
- In that case, there is a lot of jargon, very specific to the job and I'm not sure DeepL is gonna do that great (for example, DeepL might choose different words to translate _réseau_ ou _ligne_ depending on the context)
- In any case, DeepL is gonna loose all the Markdown annotations which might take some significant time to put them back

**Comment by woshilapin** [comment]
OK, no interactions in about 9 months, it probably means no interest in it: I'm closing it. I hope other 9 months deliveries will be more successful :stuck_out_tongue_closed_eyes:

**Comment by prhod** [comment]
I'm reopening this PR, I want this update to be completed, just need time for this ...

**Comment by woshilapin** [comment]
I've just found out about https://gitlocalize.com which might help us get where we want in incremental steps...

**Comment by woshilapin** [comment]
More than a year later, still nothing happened, so I'll close that one again.

**Pull request closed without merging**
